### ISSUE TITLE
Show absence of a segment in the map

### ISSUE THREAD

**Issue by small-smew** [clld/phoible#31]
I'd like the option of showing all languages in the map for a given segment, marking which languages have it and which do not, so as to show how common it is in a given area. Right now the density of dots on the map conflates sampling density and commonness of the segment.

**Comment by bambooforest** [comment]
You might refer to:

https://github.com/bambooforest/visualizing-typology-data

and the corresponding paper:

https://www.aclweb.org/anthology/L18-1129.pdf

**Comment by xrotwang** [comment]
Due to the way PHOIBLE is created - as compilation of published, often regional inventory collections (see https://phoible.org/contributors) - there will always be some sample bias in a map showing "all languages in PHOIBLE". Using "all languages" - say - from Glottolog as baseline isn't a clear-cut solution either, because PHOIBLE also has inventories for dialects. Thus, to get a meaningful map showing "commonness of a segment" will require making some judgement calls, taking into account the particular region being mapped, etc. - something that is out of scope for the PHOIBLE web app.
